--- #YAML:1.0
name:               ShiftJIS-CP932-MapUTF
version:            1.03
abstract:           transcode between Microsoft CP932 and Unicode
author:
    - SADAHIRO Tomoyuki <SADAHIRO@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    bytes:       0
    Carp:        0
    DynaLoader:  0
    Exporter:    0
    File::Copy:  0
    strict:      0
    vars:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
